---
# overlay staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secret-ns
bases:
- ../../base
resources:
- sealedsecret.yml
secretGenerator:
- name: james-other-secrets
  envs:
  - .env.secret
patchesStrategicMerge:
- deployment.yml
- ingress.yml
