apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: james-secrets
  namespace: kustomize-secret
spec:
  encryptedData:
    secret: AgCqNWi+smgqZ+SPDdwO+jbnTwwSZIg0WfTmyBx4j8+1wsfmyHlyRhVdpkOmrgoqorGAFICoW7pW3tQ31VuxYynlGWSES5M6KqaDQAd2bI3RMArOej9IHnuRHa9Yl+C7OGO+9E+CUa3L8Ge8TAB63KNDBOS22pbJMSaPTc7xMEH3TuFvfQB5s46U8nsyts/2UfQj9MY1UcUmIYOlwoipN1Qf3zSDEt7QbT3il9gTIw5zuPRAE2tM8nR3DXEJeMvVj2NPmmm5O60u9pAsA6pIMkU2z1ziMtMaTC5oWonSjFZ85/wPz9MDox3lJ/AjikrCBM7jzUjKP7jO6u178cpDkkgHUU19GiWMhKp9dNlC8QIB3oGQLB9E3S1K4KpHRf6hj4QLB1IMeJcnQTlD9XLK+shOTrubmzxl1U/S4y/ugzN10TDSgTGQXlTDln78Y5N3LLDG9Q1jQAN9it2iNGCx283zwZLrob0r9HGjnCI34YwN8RGR4FADDvBVLkcfkIr66m82MonfWkgaIJXqdUcvbIBQ/ZDZfb18lsZzmSWs9flevi3MoHTKzbd/QQaWI6Z5Gfzkzr5GRcZvb1DmbPVrHgeh9udeCw5UNphR8fu8fCC/b1iZdJlcpnKHIpbbvOzfx3ADl0BCnQ3FG5lSEaWeDe8MscydRlDnJDKJn5JeVPm4SiMfeESzVBz3wm+JVzEGPA/0R67N8u0ZIW8Udokpj9h3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: james-secrets
      namespace: kustomize-secret

