{{- if .Values.sealedSecret.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "balrog.fullname" . }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "balrog.labels" . | nindent 4 }}
spec:
  encryptedData:
    foo: {{ .Values.sealedSecret.secretFoo }}
  template:
    metadata:
      creationTimestamp: null
      name: mon-secret
      labels:
        {{- include "balrog.labels" . | nindent 8 }}

{{- end }}