{{- if .Values.sealedSecret.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: james-secrets
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "balrog.labels" . | nindent 4 }}
spec:
  encryptedData:
    secret: {{ .Values.sealedSecret.secretFoo }}
  template:
    metadata:
      name: james-secrets
      namespace: demo02-helm-dev
      labels:
        {{- include "balrog.labels" . | nindent 8 }}

{{- end }}
